### ISSUE TITLE
Docs: Triple "/" in mysql:/// doesn't work

### ISSUE THREAD

**Issue by mirao** [thiagodp/codeceptjs-dbhelper#1]
The Example 1 in [README](../blob/master/README.md) contains the connection string `mysql:///root:mypassword@localhost:3306/testdb`.

But it doesn't work for me. If I try it, I get the error `ER_ACCESS_DENIED_ERROR: Access denied for user '/root'@'1.2.3.4' (using password: YES)` because one "/" is parsed as a part of username

Double "/" works for me: `"mysql://root:mypassword@localhost:3306/testdb"`

**Used SW:**
- codeceptjs 1.4.3
- codeceptjs-dbhelper 1.0.0
- database-js-mysql 1.1.3
- database-js 3.0.8
- Ubuntu 18.10

**Comment by thiagodp** [comment]
Done. Thanks.
