### ISSUE TITLE
How to create custom assertions?

### ISSUE THREAD

**Issue by ansonliao** [thiagodp/codeceptjs-dbhelper#10]
Dear @thiagodp , 
thanks for your great work on this helpful plugin for CodeceptJS and I would like to create my custom assertion, could you kindly help to provide the tutorial on this?
Thanks.

**Comment by thiagodp** [comment]
Hello @ansonliao,

you mean assertions for query/command results, right? What do you have in mind (for instance)?

BTW, there is an assertion library for [CodeceptJS with Chai](https://codecept.io/community-helpers/#assertion-validations) that can help to compare things.

**Comment by ansonliao** [comment]
Hi @thiagodp , I think I created the wrong issue for you, yes I should create this question in [CodeceptJS with Chai](https://github.com/SitamJana/codeceptjs-chai#readme), I am very sorry for my fault.

**Comment by thiagodp** [comment]
Hi, @ansonliao, no problem. 👍
