### ISSUE TITLE
not able to install database-js sqlite

### ISSUE THREAD

**Issue by sumiagar** [thiagodp/codeceptjs-dbhelper#2]
I am trying to follow your steps. but not able to install database-js sqlite

**Comment by thiagodp** [comment]
Hello @sumiagar ,

what is the error that you are getting? Did you try to _copy-and-paste_ the installation command?

I tried it here and had no problem:
```bash
npm install --save-dev database-js-sqlite
```

**Comment by thiagodp** [comment]
I'm closing this issue due to the lack of response. Please reopen it whether really needed.
