### ISSUE TITLE
{Question} does it Support Oracle Client

### ISSUE THREAD

**Issue by MaxTester1** [thiagodp/codeceptjs-dbhelper#4]
Hi

Does this library support Oracle client?

Thnaks

**Comment by thiagodp** [comment]
Hi @MaxTester1,

[database-js](https://github.com/mlaanderson/database-js) does not support Oracle *yet*. However, [adding a new driver to support it](https://github.com/mlaanderson/database-js/wiki/Drivers#implementing-a-new-driver) is not that hard, whether you already know how to handle the target database using JS.
