### ISSUE TITLE
current version doesn't support codeceptJS 3

### ISSUE THREAD

**Issue by SolPistaqio** [thiagodp/codeceptjs-dbhelper#5]
Hey Thiago, 
thanks for the helper. But it seems it doesn't work since codepectJS 3. It says "Error: old CodeceptJS v2 format detected. Upgrade your project to the new format -> https://bit.ly/codecept3Up" and auto-updater doesn't help much. Would be really nice if you upgrade this helper to support codeceptJS 3

**Comment by thiagodp** [comment]
Hi @SolPistaqio, it does work with CodeceptJS 3. You have to write your tests with a different notation:

Instead of 
```js
Scenario('test something', async ( I ) => {   // CodeceptJS 2 notation
   /* ... */
} ); 
```

write

```js
Scenario('test something', async ( { I } ) => {  // CodeceptJS 3 notation, with "I" inside an object
   /* ... */
} ); 
```

The same notation applies to events like `BeforeSuite` and `AfterSuite`.


I'll upgrade the documentation to show examples with the new syntax.
